name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: echo "No dependencies required for static HTML"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
Create and activate main deploy workflow (buddhi-deploy.yml) for GitHub Pages publishing.
- Replaces old buddhi-sync.yml
- Sets up Node.js environment
- Deploys root-level static HTML using GitHub Actions
